from source.domain.entities.address import Address
from source.domain.entities.client import Client
from source.domain.entities.delivery_zone import DeliveryZone
from source.domain.entities.order import Order
from source.domain.entities.order_product import OrderProduct
from source.domain.entities.product import Product
from source.domain.entities.route import Route
from source.domain.entities.segment import Segment
from source.domain.entities.segment_statistics import SegmentStatistics
from source.domain.entities.vehicle import Vehicle
