from source.load_config import (
    YANDEX_GEO_API_KEY,
    YANDEX_ROUTING_API_KEY,
    ORS_ROUTING_API_KEY,
    DB_PATH,
    DEPOT_ADDRESS,
    DEFAULT_SHIFT_START_B,
    DEFAULT_SHIFT_START_C,
    DEFAULT_SHIFT_DURATION_B,
    DEFAULT_SHIFT_DURATION_C,
    ALLOW_OVERNIGHT_ROUTES_B,
    ALLOW_OVERNIGHT_ROUTES_C
)
